export const prompt = {
  resumeAnalysis: (jobDesc, resumeJSON) => {
    return `As an experienced Applicant Tracking System (ATS) analyst, and more than 20 years of experience as a Hiring manager and technical recruiter and talent acquisition, with profound knowledge in technology, software engineering, data science, full stack web development, cloud engineer, cloud developers, devops engineer and big data engineering, your role involves evaluating resumes against job descriptions. Recognizing the competitive job market, provide top-notch assistance for resume improvement. Your goal is to analyze the resume against the given job description, Analyze the following RESUME JSON based on the JOB DESCRIPTION provided. assign a percentage match based on key criteria, and pinpoint missing keywords accurately.\n\n JOB DESCRIPTION:\n "${jobDesc}"\n\n RESUME JSON:\N "${JSON.stringify(
      resumeJSON
    )}"\n\n REMEMBER, the evaluation will be done on the following core-criteria, score range of each criteria is range between 0 to 5:\n\n 1. Keyword Match: Measures the frequency and relevance of keywords from the job description in the resume.\n 2. Skill Alignment: Assesses the alignment between the candidate's skills and the required skills for the position.\n 3. Experience Relevance: Evaluate how well the candidate's work experience matches the job's responsibilities.\n 4. Education and Certifications: Checks for relevant educational qualifications and certifications.\n 5. Quantifiable Achievements: Assesses the candidate's ability to demonstrate measurable results in their previous roles.\n Additionally, evaluate the resume on these soft-criteria, score range of each criteria is range between 0 to 5:\n\n 1. Cultural Fit: Evaluates how well the candidate's personality and values align with the company culture.\n 2. Communication Skills: Assesses the candidate's ability to communicate effectively, both verbally and in writing.\n 3. Problem-Solving Skills: Evaluate the candidate's ability to identify and solve problems.\n 4. Adaptability: Assesses the candidate's ability to adapt to new situations and challenges.\n 5. Career Progression: Assesses the candidate's potential for growth and development within the organization.\n\n I want the response in one single string having the structure as per the following JSON format:\n {\n keyWordsMatch: integer,\n skillsMatch: integer,\n experienceMatch: integer,\n qualificationMatch: integer,\n quantifiableMatch: integer,\n culturalMatch: integer,\n communicationSkillMatch: integer,\n problemSolvingSkillMatch: integer,\n adaptabilityMatch: integer,\n careerProgressionMatch: integer,\n missingKeyWordsMatch: []\n }\n
    `;
  },
  resumeParser: () => {
    return``;
  },
};
